name: Web backend Build
on: 
  push:
    branches: [ master ]
    paths:
    - src/Web/React/**
    - .github/workflows/web-backend.yml
    paths-ignore:
    - src/Web/React/ClientApp/**
    
  pull_request:
    branches: [ master ]
    paths:
    - src/Web/React/**
    - .github/workflows/web-backend.yml
    paths-ignore:
    - src/Web/React/ClientApp/**
    
jobs:
  Build_web-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
            dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src/Web/React
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: ./src/Web/React